# Generated by Django 2.2.6 on 2019-10-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('work_time', models.CharField(max_length=100)),
                ('longitude', models.FloatField(max_length=20)),
                ('latitude', models.FloatField(max_length=20)),
            ],
        ),
    ]
