# Generated by Django 2.2.6 on 2019-10-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
