# Generated by Django 2.2.6 on 2019-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20191029_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField(max_length=20)),
                ('clinic_id', models.IntegerField(max_length=10)),
            ],
        ),
    ]
