# Generated by Django 2.2.6 on 2019-10-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='booking',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
