# Generated by Django 2.2.6 on 2019-10-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_auto_20191029_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateTime',
            field=models.CharField(max_length=20),
        ),
    ]
