# Generated by Django 2.2.6 on 2019-10-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_auto_20191029_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
