# Generated by Django 2.2.6 on 2019-10-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinics_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
