# Generated by Django 2.2.6 on 2019-11-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_auto_20191030_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='clinic_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
