# Generated by Django 2.2.7 on 2019-11-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_booking_bookedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notification',
            field=models.IntegerField(default=0),
        ),
    ]
