# Generated by Django 2.2.7 on 2019-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_booking_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='clinic_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
