# Generated by Django 2.2.7 on 2019-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0014_booking_clinic_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='notification',
            new_name='notificated',
        ),
        migrations.AddField(
            model_name='booking',
            name='notification_close',
            field=models.IntegerField(default=0),
        ),
    ]
