# Generated by Django 2.2.7 on 2019-11-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0016_remove_booking_notificated'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='introduction',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
