# Generated by Django 2.2.7 on 2019-11-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0017_clinics_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='introduction',
            field=models.TextField(max_length=1000),
        ),
    ]
