# Generated by Django 2.2.7 on 2019-11-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0018_auto_20191112_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinics',
            name='alias',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
