# Generated by Django 2.2.7 on 2019-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20191108_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
