# Generated by Django 2.2.6 on 2019-11-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='name',
        ),
        migrations.AddField(
            model_name='accounts',
            name='birth',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accounts',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
