# Generated by Django 2.2.6 on 2019-11-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191104_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
